//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulinaryBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeImages
    {
        public int ImageID { get; set; }
        public int RecipeID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
