//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CulinaryBook.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTags
    {
        public int RecipeTagID { get; set; }
        public int RecipeID { get; set; }
        public int TagID { get; set; }
    
        public virtual Recipes Recipes { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
